services:
  devcontainer:
    build: .
    privileged: true
    environment:
      PANGEE_CLUSTER_LOGRUS_LEVEL: trace
      PANGEE_CLUSTER_ADMIN_LOGRUS_LEVEL: trace
      PANGEE_CLUSTER_DEFAULT_ADMIN_PASSWORD: 2432612431302464617343536e4858706f567278764f532f5274752f755a526c72694f30306d73456657674c7a39644b712f43436c6d64544e506375
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/workspaces:cached
      - "/etc/resolv.conf:/etc/resolv.conf"
    ports:
      - "3322:22"
